/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.IncidentApi
import org.openapitools.client.models.CommonErrorResponse
import org.openapitools.client.models.IncidentDeleteReportRequest
import org.openapitools.client.models.IncidentHelpRequest
import org.openapitools.client.models.IncidentQueryHelpRequest
import org.openapitools.client.models.IncidentQueryHelpResponse
import org.openapitools.client.models.IncidentQueryRequest
import org.openapitools.client.models.IncidentQueryResponse
import org.openapitools.client.models.IncidentReportRequest
import org.openapitools.client.models.IncidentReportResponse

class IncidentApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of IncidentApi
        //val apiInstance = IncidentApi()

        // to test incidentHelpPost
        should("test incidentHelpPost") {
            // uncomment below to test incidentHelpPost
            //val request : IncidentHelpRequest =  // IncidentHelpRequest | Help request
            //apiInstance.incidentHelpPost(request)
        }

        // to test incidentHelpQueryPost
        should("test incidentHelpQueryPost") {
            // uncomment below to test incidentHelpQueryPost
            //val request : IncidentQueryHelpRequest =  // IncidentQueryHelpRequest | Query help request
            //val result : kotlin.collections.List<IncidentQueryHelpResponse> = apiInstance.incidentHelpQueryPost(request)
            //result shouldBe ("TODO")
        }

        // to test incidentImageIncidentIdGet
        should("test incidentImageIncidentIdGet") {
            // uncomment below to test incidentImageIncidentIdGet
            //val incidentId : kotlin.String = incidentId_example // kotlin.String | Incident ID
            //val result : kotlin.String = apiInstance.incidentImageIncidentIdGet(incidentId)
            //result shouldBe ("TODO")
        }

        // to test incidentQueryPost
        should("test incidentQueryPost") {
            // uncomment below to test incidentQueryPost
            //val request : IncidentQueryRequest =  // IncidentQueryRequest | Query request
            //val result : IncidentQueryResponse = apiInstance.incidentQueryPost(request)
            //result shouldBe ("TODO")
        }

        // to test incidentReportDelete
        should("test incidentReportDelete") {
            // uncomment below to test incidentReportDelete
            //val request : IncidentDeleteReportRequest =  // IncidentDeleteReportRequest | Delete report request
            //apiInstance.incidentReportDelete(request)
        }

        // to test incidentReportPost
        should("test incidentReportPost") {
            // uncomment below to test incidentReportPost
            //val request : IncidentReportRequest =  // IncidentReportRequest | Report request
            //val result : IncidentReportResponse = apiInstance.incidentReportPost(request)
            //result shouldBe ("TODO")
        }

    }
}
