// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DeltaLaboratory/incident-api/internal/ent/incident"
	"github.com/DeltaLaboratory/incident-api/internal/ent/predicate"
	"github.com/DeltaLaboratory/incident-api/internal/ent/schema"
	"github.com/google/uuid"
)

// IncidentUpdate is the builder for updating Incident entities.
type IncidentUpdate struct {
	config
	hooks    []Hook
	mutation *IncidentMutation
}

// Where appends a list predicates to the IncidentUpdate builder.
func (iu *IncidentUpdate) Where(ps ...predicate.Incident) *IncidentUpdate {
	iu.mutation.Where(ps...)
	return iu
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (iu *IncidentUpdate) SetIdempotencyKey(s string) *IncidentUpdate {
	iu.mutation.SetIdempotencyKey(s)
	return iu
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (iu *IncidentUpdate) SetNillableIdempotencyKey(s *string) *IncidentUpdate {
	if s != nil {
		iu.SetIdempotencyKey(*s)
	}
	return iu
}

// SetReporter sets the "reporter" field.
func (iu *IncidentUpdate) SetReporter(u uuid.UUID) *IncidentUpdate {
	iu.mutation.SetReporter(u)
	return iu
}

// SetNillableReporter sets the "reporter" field if the given value is not nil.
func (iu *IncidentUpdate) SetNillableReporter(u *uuid.UUID) *IncidentUpdate {
	if u != nil {
		iu.SetReporter(*u)
	}
	return iu
}

// SetLocation sets the "location" field.
func (iu *IncidentUpdate) SetLocation(sj *schema.GeoJson) *IncidentUpdate {
	iu.mutation.SetLocation(sj)
	return iu
}

// ClearLocation clears the value of the "location" field.
func (iu *IncidentUpdate) ClearLocation() *IncidentUpdate {
	iu.mutation.ClearLocation()
	return iu
}

// SetType sets the "type" field.
func (iu *IncidentUpdate) SetType(s string) *IncidentUpdate {
	iu.mutation.SetType(s)
	return iu
}

// SetNillableType sets the "type" field if the given value is not nil.
func (iu *IncidentUpdate) SetNillableType(s *string) *IncidentUpdate {
	if s != nil {
		iu.SetType(*s)
	}
	return iu
}

// SetDescription sets the "description" field.
func (iu *IncidentUpdate) SetDescription(s string) *IncidentUpdate {
	iu.mutation.SetDescription(s)
	return iu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (iu *IncidentUpdate) SetNillableDescription(s *string) *IncidentUpdate {
	if s != nil {
		iu.SetDescription(*s)
	}
	return iu
}

// SetImage sets the "image" field.
func (iu *IncidentUpdate) SetImage(b []byte) *IncidentUpdate {
	iu.mutation.SetImage(b)
	return iu
}

// SetCreatedAt sets the "created_at" field.
func (iu *IncidentUpdate) SetCreatedAt(t time.Time) *IncidentUpdate {
	iu.mutation.SetCreatedAt(t)
	return iu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (iu *IncidentUpdate) SetNillableCreatedAt(t *time.Time) *IncidentUpdate {
	if t != nil {
		iu.SetCreatedAt(*t)
	}
	return iu
}

// Mutation returns the IncidentMutation object of the builder.
func (iu *IncidentUpdate) Mutation() *IncidentMutation {
	return iu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (iu *IncidentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, iu.sqlSave, iu.mutation, iu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (iu *IncidentUpdate) SaveX(ctx context.Context) int {
	affected, err := iu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (iu *IncidentUpdate) Exec(ctx context.Context) error {
	_, err := iu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iu *IncidentUpdate) ExecX(ctx context.Context) {
	if err := iu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (iu *IncidentUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(incident.Table, incident.Columns, sqlgraph.NewFieldSpec(incident.FieldID, field.TypeUUID))
	if ps := iu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := iu.mutation.IdempotencyKey(); ok {
		_spec.SetField(incident.FieldIdempotencyKey, field.TypeString, value)
	}
	if value, ok := iu.mutation.Reporter(); ok {
		_spec.SetField(incident.FieldReporter, field.TypeUUID, value)
	}
	if value, ok := iu.mutation.Location(); ok {
		_spec.SetField(incident.FieldLocation, field.TypeOther, value)
	}
	if iu.mutation.LocationCleared() {
		_spec.ClearField(incident.FieldLocation, field.TypeOther)
	}
	if value, ok := iu.mutation.GetType(); ok {
		_spec.SetField(incident.FieldType, field.TypeString, value)
	}
	if value, ok := iu.mutation.Description(); ok {
		_spec.SetField(incident.FieldDescription, field.TypeString, value)
	}
	if value, ok := iu.mutation.Image(); ok {
		_spec.SetField(incident.FieldImage, field.TypeBytes, value)
	}
	if value, ok := iu.mutation.CreatedAt(); ok {
		_spec.SetField(incident.FieldCreatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, iu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{incident.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	iu.mutation.done = true
	return n, nil
}

// IncidentUpdateOne is the builder for updating a single Incident entity.
type IncidentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *IncidentMutation
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (iuo *IncidentUpdateOne) SetIdempotencyKey(s string) *IncidentUpdateOne {
	iuo.mutation.SetIdempotencyKey(s)
	return iuo
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (iuo *IncidentUpdateOne) SetNillableIdempotencyKey(s *string) *IncidentUpdateOne {
	if s != nil {
		iuo.SetIdempotencyKey(*s)
	}
	return iuo
}

// SetReporter sets the "reporter" field.
func (iuo *IncidentUpdateOne) SetReporter(u uuid.UUID) *IncidentUpdateOne {
	iuo.mutation.SetReporter(u)
	return iuo
}

// SetNillableReporter sets the "reporter" field if the given value is not nil.
func (iuo *IncidentUpdateOne) SetNillableReporter(u *uuid.UUID) *IncidentUpdateOne {
	if u != nil {
		iuo.SetReporter(*u)
	}
	return iuo
}

// SetLocation sets the "location" field.
func (iuo *IncidentUpdateOne) SetLocation(sj *schema.GeoJson) *IncidentUpdateOne {
	iuo.mutation.SetLocation(sj)
	return iuo
}

// ClearLocation clears the value of the "location" field.
func (iuo *IncidentUpdateOne) ClearLocation() *IncidentUpdateOne {
	iuo.mutation.ClearLocation()
	return iuo
}

// SetType sets the "type" field.
func (iuo *IncidentUpdateOne) SetType(s string) *IncidentUpdateOne {
	iuo.mutation.SetType(s)
	return iuo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (iuo *IncidentUpdateOne) SetNillableType(s *string) *IncidentUpdateOne {
	if s != nil {
		iuo.SetType(*s)
	}
	return iuo
}

// SetDescription sets the "description" field.
func (iuo *IncidentUpdateOne) SetDescription(s string) *IncidentUpdateOne {
	iuo.mutation.SetDescription(s)
	return iuo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (iuo *IncidentUpdateOne) SetNillableDescription(s *string) *IncidentUpdateOne {
	if s != nil {
		iuo.SetDescription(*s)
	}
	return iuo
}

// SetImage sets the "image" field.
func (iuo *IncidentUpdateOne) SetImage(b []byte) *IncidentUpdateOne {
	iuo.mutation.SetImage(b)
	return iuo
}

// SetCreatedAt sets the "created_at" field.
func (iuo *IncidentUpdateOne) SetCreatedAt(t time.Time) *IncidentUpdateOne {
	iuo.mutation.SetCreatedAt(t)
	return iuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (iuo *IncidentUpdateOne) SetNillableCreatedAt(t *time.Time) *IncidentUpdateOne {
	if t != nil {
		iuo.SetCreatedAt(*t)
	}
	return iuo
}

// Mutation returns the IncidentMutation object of the builder.
func (iuo *IncidentUpdateOne) Mutation() *IncidentMutation {
	return iuo.mutation
}

// Where appends a list predicates to the IncidentUpdate builder.
func (iuo *IncidentUpdateOne) Where(ps ...predicate.Incident) *IncidentUpdateOne {
	iuo.mutation.Where(ps...)
	return iuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (iuo *IncidentUpdateOne) Select(field string, fields ...string) *IncidentUpdateOne {
	iuo.fields = append([]string{field}, fields...)
	return iuo
}

// Save executes the query and returns the updated Incident entity.
func (iuo *IncidentUpdateOne) Save(ctx context.Context) (*Incident, error) {
	return withHooks(ctx, iuo.sqlSave, iuo.mutation, iuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (iuo *IncidentUpdateOne) SaveX(ctx context.Context) *Incident {
	node, err := iuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (iuo *IncidentUpdateOne) Exec(ctx context.Context) error {
	_, err := iuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iuo *IncidentUpdateOne) ExecX(ctx context.Context) {
	if err := iuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (iuo *IncidentUpdateOne) sqlSave(ctx context.Context) (_node *Incident, err error) {
	_spec := sqlgraph.NewUpdateSpec(incident.Table, incident.Columns, sqlgraph.NewFieldSpec(incident.FieldID, field.TypeUUID))
	id, ok := iuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Incident.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := iuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, incident.FieldID)
		for _, f := range fields {
			if !incident.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != incident.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := iuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := iuo.mutation.IdempotencyKey(); ok {
		_spec.SetField(incident.FieldIdempotencyKey, field.TypeString, value)
	}
	if value, ok := iuo.mutation.Reporter(); ok {
		_spec.SetField(incident.FieldReporter, field.TypeUUID, value)
	}
	if value, ok := iuo.mutation.Location(); ok {
		_spec.SetField(incident.FieldLocation, field.TypeOther, value)
	}
	if iuo.mutation.LocationCleared() {
		_spec.ClearField(incident.FieldLocation, field.TypeOther)
	}
	if value, ok := iuo.mutation.GetType(); ok {
		_spec.SetField(incident.FieldType, field.TypeString, value)
	}
	if value, ok := iuo.mutation.Description(); ok {
		_spec.SetField(incident.FieldDescription, field.TypeString, value)
	}
	if value, ok := iuo.mutation.Image(); ok {
		_spec.SetField(incident.FieldImage, field.TypeBytes, value)
	}
	if value, ok := iuo.mutation.CreatedAt(); ok {
		_spec.SetField(incident.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &Incident{config: iuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, iuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{incident.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	iuo.mutation.done = true
	return _node, nil
}
