// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Help is the predicate function for help builders.
type Help func(*sql.Selector)

// Incident is the predicate function for incident builders.
type Incident func(*sql.Selector)
