/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param helpId 
 * @param latitude 
 * @param longitude 
 * @param radius Radius in meters
 */


data class IncidentQueryHelpRequest (

    @Json(name = "help_id")
    val helpId: kotlin.String? = null,

    @Json(name = "latitude")
    val latitude: java.math.BigDecimal? = null,

    @Json(name = "longitude")
    val longitude: java.math.BigDecimal? = null,

    /* Radius in meters */
    @Json(name = "radius")
    val radius: kotlin.Int? = null

) {


}

