/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param description 
 * @param image Base64 encoded jpeg image
 * @param latitude 
 * @param longitude 
 * @param type 
 * @param userId user id in uuid format
 * @param userKey 32 byte ascii string
 */


data class IncidentReportRequest (

    @Json(name = "description")
    val description: kotlin.String? = null,

    /* Base64 encoded jpeg image */
    @Json(name = "image")
    val image: kotlin.String? = null,

    @Json(name = "latitude")
    val latitude: java.math.BigDecimal? = null,

    @Json(name = "longitude")
    val longitude: java.math.BigDecimal? = null,

    @Json(name = "type")
    val type: kotlin.String? = null,

    /* user id in uuid format */
    @Json(name = "user_id")
    val userId: kotlin.String? = null,

    /* 32 byte ascii string */
    @Json(name = "user_key")
    val userKey: kotlin.String? = null

) {


}

