/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.IncidentQueryHelpRequest

class IncidentQueryHelpRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of IncidentQueryHelpRequest
        //val modelInstance = IncidentQueryHelpRequest()

        // to test the property `helpId`
        should("test helpId") {
            // uncomment below to test the property
            //modelInstance.helpId shouldBe ("TODO")
        }

        // to test the property `latitude`
        should("test latitude") {
            // uncomment below to test the property
            //modelInstance.latitude shouldBe ("TODO")
        }

        // to test the property `longitude`
        should("test longitude") {
            // uncomment below to test the property
            //modelInstance.longitude shouldBe ("TODO")
        }

        // to test the property `radius` - Radius in meters
        should("test radius") {
            // uncomment below to test the property
            //modelInstance.radius shouldBe ("TODO")
        }

    }
}
