/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.IncidentDeleteReportRequest

class IncidentDeleteReportRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of IncidentDeleteReportRequest
        //val modelInstance = IncidentDeleteReportRequest()

        // to test the property `incidentId`
        should("test incidentId") {
            // uncomment below to test the property
            //modelInstance.incidentId shouldBe ("TODO")
        }

        // to test the property `userId`
        should("test userId") {
            // uncomment below to test the property
            //modelInstance.userId shouldBe ("TODO")
        }

        // to test the property `userKey`
        should("test userKey") {
            // uncomment below to test the property
            //modelInstance.userKey shouldBe ("TODO")
        }

    }
}
