/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.IncidentHelpRequest

class IncidentHelpRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of IncidentHelpRequest
        //val modelInstance = IncidentHelpRequest()

        // to test the property `bloodPressure`
        should("test bloodPressure") {
            // uncomment below to test the property
            //modelInstance.bloodPressure shouldBe ("TODO")
        }

        // to test the property `bodyTemperature`
        should("test bodyTemperature") {
            // uncomment below to test the property
            //modelInstance.bodyTemperature shouldBe ("TODO")
        }

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `heartRate`
        should("test heartRate") {
            // uncomment below to test the property
            //modelInstance.heartRate shouldBe ("TODO")
        }

        // to test the property `latitude`
        should("test latitude") {
            // uncomment below to test the property
            //modelInstance.latitude shouldBe ("TODO")
        }

        // to test the property `longitude`
        should("test longitude") {
            // uncomment below to test the property
            //modelInstance.longitude shouldBe ("TODO")
        }

        // to test the property `userId`
        should("test userId") {
            // uncomment below to test the property
            //modelInstance.userId shouldBe ("TODO")
        }

    }
}
